### ISSUE TITLE
restarting go2rtc process leaves zombie process

### ISSUE THREAD

**Issue by ivanjx** [AlexxIT/go2rtc#907] opened 2024-01-27 04:03 UTC
for some reason my frigate setup wont reconnect to the camera when it is disconnected (my cameras need to be restarted regularly to prevent random freezes). so in home assistant i created an automation script to auto restart the go2rtc process inside the frigate docker container by calling `http://frigate-container:1984/api/restart` whenever i detect the camera is disconnected. usually after 30 seconds the cameras are restored and began recording again like normal. however when i logged in to my machine i noticed there are zombie process running by the name `ffmpeg`.

![image](https://github.com/AlexxIT/go2rtc/assets/12814796/f4b4032b-c3ce-4ae1-b87e-5ae101dd1989)

**Comment by NickM-27** [comment] 2024-01-27 13:40
this is a duplicate of https://github.com/AlexxIT/go2rtc/issues/894

**Comment by ivanjx** [comment] 2024-02-06 02:01
the zombie process seems to also keep the rtsp udp ports blocked so my rtsp cameras eventually cant connect anymore. for now, running this script every minute or so helps solve the problem:
```bash
#!/bin/bash

zombies=$(ps -A -ostat,ppid,comm | awk '/[zZ]/{if ($3 == "ffmpeg") print $2}')

for zombie in $zombies
do
    sudo kill -9 $zombie
done
```

**Closed** 2024-04-23 10:52 UTC
Labels: duplicate
