### ISSUE TITLE
Transcoded audostream stutting/skipping

### ISSUE THREAD

**Issue by tungmeister** [AlexxIT/go2rtc#178] opened 2023-01-17 14:38 UTC
I'm having an issue with the transcoded audostream stuttering/skipping for WebRTC within Frigate when transcoding from AAC as can be seen here
https://github.com/blakeblackshear/frigate/issues/5124

**Comment by tungmeister** [comment] 2023-01-17 16:02
The audio stream is perfect in VLC but I have playback issues in Chrome/the Hass companion App.

**Comment by AlexxIT** [comment] 2023-01-17 16:05
Have you tried exact my url? Because it test OPUS codec in desktop app.

**Comment by tungmeister** [comment] 2023-01-17 16:06
That's what I meant. OPUS works perfectly in VLC but not in browsers.

**Comment by AlexxIT** [comment] 2023-01-17 16:29
Try it on different browsers on different devices. One user reported sound problems on Chrome and had no problems on Firefox

**Comment by tungmeister** [comment] 2023-01-17 16:33
Firefox doesn't work at all. Same problem on all devices with chrome/edge. Could it be due to it being a 4k stream?

**Comment by AlexxIT** [comment] 2023-01-17 17:46
Yes. Maybe it takes all resources for decoding video in your browser.

**Comment by tungmeister** [comment] 2023-01-17 20:27
there's no issue with MSE though? It's exactly the same regardless of device/hardware spec.

**Comment by AlexxIT** [comment] 2023-01-18 03:44
Browsers has different code for decode WebRTC and MSE. Check CPU load in both cases.

**Comment by tungmeister** [comment] 2023-01-18 12:38
Chrome is only using 3% CPU and GPU is only 14% utilised so it's not a load issue - the stuttering is the same on all devices.

**Comment by AlexxIT** [comment] 2023-01-18 13:34
I was able to catch the problem with sound on my Safari + WebRTC + PCMU. Maybe if I fix it, it will also fix your case.

**Comment by tungmeister** [comment] 2023-01-19 12:29
no issues with OPUS though? as OPUS is much better quality.

**Comment by AlexxIT** [comment] 2023-01-19 12:51
It's default format from one of my cameras.

**Comment by KingOfBaboon** [comment] 2023-03-09 01:08
also experiencing similar audio stream stuttering/skipping but for non-transcoded:

camera: tapo c210
laptop: mac m1
browsers: chrome, safari, edge
go2rtc version: 1.20
audio stream from the camera: pcma/8000(confirmed from VLC)

with simple config like 
```
streams:
  living_room: rtsp://xxxx@192.168.1.xxx/stream1
```
 The audio out of HA `type: custom:webrtc-camera` card and browser tabs like `http://192.168.1.xxx:1984/stream.html?src=living_room&mode=webrtc` are stuttering/skipping. Same as in the Android HA app.

But the rtsp links from `http://192.168.1.xxx:1984/links.html?src=living_room` take me to mac VLC app where the audio is perfect. Also audio sounds good from Android tapo app.

Is there a way to confirm how browsers decode and playback those `pcma/8000` stream?

**Comment by CV8R** [comment] 2023-07-02 12:41
Same problem/symptoms (corrupted Opus) when transcoding from AAC.  Affects  WebRTC on Chrome + Firefox + live_provider: webrtc-card. VLC is okay using `rtsp://<address>:8554/<camera>?video&audio=opus`

**Comment by AlexxIT** [comment] 2023-07-16 11:27
Should be fixed: https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0

**Closed by AlexxIT** 2023-07-16 11:27 UTC
Labels: question
