### ISSUE TITLE
Error: RTP header size insufficient for extension

### ISSUE THREAD

**Issue by gcortes** [AlexxIT/go2rtc#420] opened 2023-05-06 01:45 UTC
I'm using go2rtc bundled with Frigate. When I bring up Frigate I get the following errors in the go2rtc log:

```
2023-05-05 13:08:24.622564176  [INFO] Preparing go2rtc config...
2023-05-05 13:08:24.984340158  [INFO] Starting go2rtc...
2023-05-05 13:08:25.066940427  13:08:25.066 INF go2rtc version 1.2.0 linux/amd64
2023-05-05 13:08:25.067284885  13:08:25.067 INF [api] listen addr=:1984
2023-05-05 13:08:25.067754446  13:08:25.067 INF [rtsp] listen addr=:8554
2023-05-05 13:08:25.068289373  13:08:25.068 INF [srtp] listen addr=:8443
2023-05-05 13:08:25.068653837  13:08:25.068 INF [webrtc] listen addr=:8555
2023-05-05 13:08:34.628404338  [INFO] Starting go2rtc healthcheck service...
2023-05-05 13:09:43.125095785  13:09:43.124 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="size 61343 < 185640: RTP header size insufficient for extension" url=rtsp://home_assistant:W6!KzBEWiT3rzMg9@10.0.0.111:554/Streaming/Channels/101
2023-05-05 13:10:45.725703414  13:10:45.725 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.24.0.2:42078->10.0.0.108:554: read: connection reset by peer" url=rtsp://home_assistant:W6!KzBEWiT3rzMg9@10.0.0.108:554/Streaming/Channels/101
2023-05-05 13:17:01.432985194  13:17:01.432 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="buffer too small" url=rtsp://home_assistant:W6!KzBEWiT3rzMg9@10.0.0.106:554/Streaming/Channels/101
```
The camera is a HIKVision. I'm running Frigate in Docker on Ubuntu on a Mac Mini (Intel). It's version 1.2.

I would try a newer version of go2rtc if I knew which one. Would it be go2rtc_linux_amd64? Has the problem already been fixed since 1.2?

**Comment by AlexxIT** [comment] 2023-05-06 03:52
I think you just have broken stream. Try to use ffmpeg source.
Does the camera work over wifi?

**Comment by gcortes** [comment] 2023-05-06 05:24
The eight cameras are connected via Ethernet. I didn't show the full log as the errors were the same. They all have the same error.

ffmpeg source. Sorry, try using it where? 

I'm also running a separate app, Viewcam, to display feeds from the cameras. It works fine. It's using RTSP.

**Comment by AlexxIT** [comment] 2023-05-06 06:16
I can see three different network errors in different time. Maybe it's your network setup issue.
How do you run Ubuntu on a Mac? Is it virtualization?

https://github.com/AlexxIT/go2rtc#source-rtsp
> - If the stream from your camera is glitchy, try using [ffmpeg source](https://github.com/AlexxIT/go2rtc#source-ffmpeg). It will not add CPU load if you won't use transcoding
> - If the stream from your camera is very glitchy, try to use transcoding with [ffmpeg source](https://github.com/AlexxIT/go2rtc#source-ffmpeg)

**Comment by gcortes** [comment] 2023-05-06 14:57
I'm running directly on the hardware. I can't even boot MacOS.
My Viewcam feeds were locking up after getting go2rtc running. I tried stopping Viewcam and restarting Frigate. I still get the errors.

I believe I'm already using an ffmpeg source. This is the config for one of my cameras in Frigate:
```
cameras:
  drive_way:
    ffmpeg:
      inputs:
#        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
        - path: rtsp://127.0.0.1:8554/drive_way_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
        - path: rtsp://127.0.0.1:8554/drive_way
          input_args: preset-rtsp-restream
          roles:
            - record
```
I'm also getting errors in my Frigate log regarding ffmpeg. Here's some of them:

```
2023-05-06 07:32:20.885476656  [2023-05-06 07:32:20] watchdog.south_yard            INFO    : south_yard exceeded fps limit. Exiting ffmpeg...
2023-05-06 07:32:20.886469497  [2023-05-06 07:32:20] watchdog.south_yard            INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-06 07:32:20.998587202  [2023-05-06 07:32:20] frigate.video                  ERROR   : south_yard: Unable to read frames from ffmpeg process.
2023-05-06 07:32:20.998600582  [2023-05-06 07:32:20] frigate.video                  ERROR   : south_yard: ffmpeg process is not running. exiting capture thread...
2023-05-06 07:32:31.054714994  [2023-05-06 07:32:31] watchdog.south_yard            ERROR   : Ffmpeg process crashed unexpectedly for south_yard.
2023-05-06 07:32:31.055079595  [2023-05-06 07:32:31] watchdog.south_yard            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-06 07:32:31.055484689  [2023-05-06 07:32:31] ffmpeg.south_yard.detect       ERROR   : [swscaler @ 0x558de1459cc0] [swscaler @ 0x558de1466cc0] deprecated pixel format used, make sure you did set range correctly
```

**Comment by AlexxIT** [comment] 2023-05-07 08:21
Try to run go2rtc on any other computer in your home. And check if you have problems.

"fatal error" is critical problem, but it may be fixed in latest version. As I know, you using old v1.2 version

**Comment by gcortes** [comment] 2023-05-07 15:56
My other computers run MacOS and I only use go2rtc with Frigate. I've backed it out of my Frigate config and all the Frigate errors have gone away. My viewcam app video feeds from the same camera still lock up every few hours so I'm not completely problem free. I'll try again in some future release of Frigate as I had no pressing need for it. You can close this issue installation specific if you like. Thanks for your help.

**Comment by AlexxIT** [comment] 2023-05-07 17:48
go2rtc support all popular OS, even macOS. It's up to you whether you want to find the cause of the problem or not.

**Closed by AlexxIT** 2023-05-07 17:48 UTC
Labels: question

**Comment by gcortes** [comment] 2023-05-09 16:37
Curiosity got the better of me. I decided to try to run it on my Mac Pro. The quick start instructions say to download it and then access it via a browser. There must be some other steps. I unzipped the zip file. MacOS thinks it's a document. Do I put it in the applications folder or some other place? Do I then start it? I saw the line about changing the execution permissions. Finally, is there some 'slow start' documentation somewhere that describes it in more detail?

**Comment by AlexxIT** [comment] 2023-05-09 16:49
You need to run from terminal `chmod +x go2rtc...`
Also macOS will block app from run.
https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html

**Comment by gcortes** [comment] 2023-05-09 17:57
I got it running and added three cameras. They all provide a stream. Is there some where to see the log to see if there are any errors? I'll add the rest of the cameras that are in my Frigate config.

**Comment by gcortes** [comment] 2023-05-09 19:29
If you mean the Terminal session where go2rtc was invoked then I'm not seeing any errors. I've added all the cameras I have defined in Frigate and go2rtc has been running for an hour with a stream being displayed. The Mac Pro on which go2rtc is running, all the cameras, and the Mac Mini running Ubuntu and the the Frigate Docker image are all connected to the same switch via Ethernet cables.

**Comment by AlexxIT** [comment] 2023-05-10 03:12
Problems appear when the number of cameras increases?

**Comment by AlexxIT** [comment] 2023-05-11 02:49
Do you have docker network host option with your setup?

**Comment by AlexxIT** [comment] 2023-05-11 15:36
You haven't snow your go2rtc config section inside frigate

**Comment by AlexxIT** [comment] 2023-05-11 20:40
So go2rtc config it's just direct links to RTSP. OK.

What about ffmpeg CPU usage when you set direct links to cameras right in Frigate cameras section?
Your CPU usage VERY high. It may be case of problems.

What exact CPU model in your Mac Mini?

**Comment by gcortes** [comment] 2023-05-11 21:54
I don't know the year of the Mac Mini, but must be seven to ten years old. I switched back to the direct links. It made a big difference:

```
top - 14:50:55 up 10 days,  9:05,  2 users,  load average: 4.16, 12.02, 15.94
Tasks: 424 total,   1 running, 423 sleeping,   0 stopped,   0 zombie
%Cpu(s): 12.2 us,  5.6 sy,  0.0 ni, 80.6 id,  0.1 wa,  0.0 hi,  1.4 si,  0.0 st
MiB Mem :  15915.0 total,   1045.3 free,   2259.0 used,  12610.7 buff/cache
MiB Swap:  16290.0 total,  16157.2 free,    132.8 used.  13031.4 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 690446 root      20   0 1500480  98308  16088 S  18.9   0.6   0:19.65 frigate.process
 690508 root      20   0  443220  29820  17816 S  11.3   0.2   0:14.10 ffmpeg
 690513 root      20   0  443084  29760  17784 S  11.3   0.2   0:13.57 ffmpeg
 690437 root      20   0 1217976 110412  21528 S   9.9   0.7   0:12.71 frigate.detecto
 690109 root      20   0 2832108 153324  58248 S   7.9   0.9   0:11.22 python3
 690452 root      20   0 1500744  97480  15284 S   7.0   0.6   0:11.23 frigate.process
 690465 root      20   0  443012  29868  18064 S   5.3   0.2   0:06.37 ffmpeg
 690501 root      20   0  443048  29180  17400 S   4.0   0.2   0:05.07 ffmpeg
 690498 root      20   0  130496  23860  17328 S   3.3   0.1   0:03.81 ffmpeg
 690484 root      20   0  131208  24700  17268 S   3.0   0.2   0:03.92 ffmpeg
 690511 root      20   0  132156  25664  17360 S   3.0   0.2   0:03.90 ffmpeg
 688797 root      20   0 1681676 364172  62184 S   2.6   2.2   1:14.07 python3
 690439 root      20   0 1574092  93228  11456 S   2.6   0.6   0:03.34 frigate.output
```
All my streams in Frigate are clean and not lagging.

**Comment by AlexxIT** [comment] 2023-06-26 14:11
Please reopen issue if it still exist on v1.5
