### ISSUE TITLE
Latency increasing after long period operation

### ISSUE THREAD

**Issue by saeyongpark** [AlexxIT/go2rtc#673] opened 2023-10-05 06:55 UTC
Hi AlexxIT,
I built a gstreamer rtsp server and downloaded pre-built go2rtc_linux_arm64.
go2rtc worked properly with very low latency and I appreciated for that.
But after like a day, latency was increased like 2 seconds.
I checked rtsp stream with gstream rtspsrc command it worked properly, but in api page(:1984) the stream has latency.
Any reason for that?
I checked other issues but can't find this phenomenon and I checked info in api page it seems webrtc udp4 works properly.

I set stream as like below
streams:
  camera: rtsp://127.0.0.1:8554/test

Thank you!

**Comment by AlexxIT** [comment] 2023-10-05 07:41
What the source of your stream?

**Comment by saeyongpark** [comment] 2023-10-05 07:58
It's from gstreamer rtsp server which works like IP camera and stream encoded with H264. Gstremaer rtsp server get streams from other cameras.

**Comment by AlexxIT** [comment] 2023-10-05 09:08
Latency may increasing between:
- camera => go2rtc
- go2rtc => browser/other client

**Comment by saeyongpark** [comment] 2023-10-05 09:58
Thank you for your reply.
In go2rtc=>browser/other client case, is there anything that I can do to keep the low latency?

**Comment by AlexxIT** [comment] 2023-10-05 10:11
Latency can be only from TCP connection (MSE/MP4/WebRTC TCP).
Latency should no be from WebRTC UDP connection

**Comment by saeyongpark** [comment] 2023-10-05 10:18
Can I make WebRTC works as UDP via modification of yaml file?
I'll look into RTSP, if I get something I'll report it here

**Comment by AlexxIT** [comment] 2023-10-05 10:24
WebRTC will auto choose technology based on your network capabilities.

**Comment by saeyongpark** [comment] 2023-10-05 10:28
Great, thanks a lot!!

**Comment by rbray89** [comment] 2024-04-17 15:22
Seeing the same issue with some reolink cameras. Initially fine, but after a day or two, latency climbs to several seconds. Web stream from the camera UI seems fine, so I'm not sure where it is being introduced.

**Comment by AlexxIT** [comment] 2024-04-20 09:08
@rbray89 This is known problem for Reolink cameras. Awful RTSP TCP realisation. Can be fixed via using RTSP UDP, but go2rtc doesn't support it directly for now.

**Comment by AlexxIT** [comment] 2024-05-28 14:34
Please let me know if the problem is relevant

**Closed by AlexxIT** 2024-05-28 14:34 UTC
Labels: question
